// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTodo(arg1) {
  return window['go']['main']['repository']['AddTodo'](arg1);
}

export function DeleteTodo(arg1) {
  return window['go']['main']['repository']['DeleteTodo'](arg1);
}

export function ListTodo() {
  return window['go']['main']['repository']['ListTodo']();
}
